# Puerto del servidor
server.port=${PORT:8080}
spring.application.name=MaintenanceSystem

# Perfil activo (cambiar a 'aiven' cuando uses cloud)
spring.profiles.active=local


# Configuración común
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Desarrollo
spring.thymeleaf.cache=false
spring.jpa.show-sql=true