<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.cornerstone</groupId>
        <artifactId>property</artifactId>
        <version>1.0-SNAPSHOT</version>

    </parent>

    <artifactId>persistence</artifactId>

    <dependencies>
        <!-- 1. Acceso a las clases de tu dominio (Tenant) -->
        <dependency>
            <groupId>com.cornerstone</groupId>
            <artifactId>domain</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>



        <!-- 2. Spring Data JPA (@Entity, @Table, Repositorios) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <!-- 3. Driver de conexión a MySQL -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>

        <!-- Permite a la persistencia ver las interfaces de la capa de Aplicación -->
        <dependency>
            <groupId>com.cornerstone</groupId>
            <artifactId>application</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

</project>